# Map ID to human-readable names conversion
MAP_NAMES = {
    # Standard maps
    0: "Big Race",
    1: "New Dawn", 
    2: "Fault Line",
    3: "Two Brothers",
    4: "Islands of Ice",
    5: "Hotspot",
    6: "Shatter",
    7: "North",
    8: "Land of Fire",
    9: "Neighbours",
    10: "Sea of Fortune",
    11: "Ocean",
    12: "Trap",
    13: "Two Brothers",  # 20_NE_two_brothers
    14: "Warrior's Path",
    15: "Mountain Range",
    16: "Atlantic",
    17: "Estuary",
    18: "Crucible",
    19: "Sleeping Giant",
    20: "Korea",
    21: "Haven",
    22: "Tears of the Desert",
    23: "Mountain Range",
    24: "Crucible",
    25: "Sleeping Giant",
    26: "Shatter",
    27: "Northern Lights",
    28: "Loop",
    29: "Helena",
    30: "Crash Zone Alpha",
    31: "Crash Zone Bravo",
    32: "Crash Zone Charlie",
    33: "Crash Zone Delta",
    34: "Faroe Islands",
    35: "Fiji Islands",
    36: "Greece",
    37: "Iceland",
    38: "Japan",
    39: "Malta",
    40: "Monaco",
    41: "Naples",
    42: "Northern Lights",
    43: "Oslo",
    44: "Panama",
    45: "Philippines",
    46: "Portugal",
    47: "Scotland",
    48: "Spain",
    49: "Sweden",
    50: "Switzerland",
    51: "Turkey",
    52: "UK",
    53: "USA",
    54: "USSR",
    55: "Venezuela",
    56: "Yugoslavia",
}

# Map display name to clean name conversion
MAP_DISPLAY_NAMES = {
    "20_NE_two_brothers": "Two Brothers",
    "10_NA_big_race": "Big Race",
    "11_NA_new_dawn": "New Dawn",
    "12_NA_fault_line": "Fault Line",
    "13_NE_two_brothers": "Two Brothers",
    "14_NA_islands_of_ice": "Islands of Ice",
    "15_NA_hotspot": "Hotspot",
    "16_NA_shatter": "Shatter",
    "17_NA_north": "North",
    "18_NA_land_of_fire": "Land of Fire",
    "19_NA_neighbours": "Neighbours",
    "20_NA_sea_of_fortune": "Sea of Fortune",
    "21_NA_ocean": "Ocean",
    "22_NA_trap": "Trap",
    "23_NA_warriors_path": "Warrior's Path",
    "24_NA_mountain_range": "Mountain Range",
    "25_NA_atlantic": "Atlantic",
    "26_NA_estuary": "Estuary",
    "27_NA_crucible": "Crucible",
    "28_NA_sleeping_giant": "Sleeping Giant",
    "29_NA_korea": "Korea",
    "30_NA_haven": "Haven",
    "31_NA_tears_of_the_desert": "Tears of the Desert",
    "32_NA_mountain_range": "Mountain Range",
    "33_NA_crucible": "Crucible",
    "34_NA_sleeping_giant": "Sleeping Giant",
    "35_NA_shatter": "Shatter",
    "36_NA_northern_lights": "Northern Lights",
    "37_NA_loop": "Loop",
    "38_NA_helena": "Helena",
    "39_NA_crash_zone_alpha": "Crash Zone Alpha",
    "40_NA_crash_zone_bravo": "Crash Zone Bravo",
    "41_NA_crash_zone_charlie": "Crash Zone Charlie",
    "42_NA_crash_zone_delta": "Crash Zone Delta",
    "43_NA_faroe_islands": "Faroe Islands",
    "44_NA_fiji_islands": "Fiji Islands",
    "45_NA_greece": "Greece",
    "46_NA_iceland": "Iceland",
    "47_NA_japan": "Japan",
    "48_NA_malta": "Malta",
    "49_NA_monaco": "Monaco",
    "50_NA_naples": "Naples",
    "51_NA_northern_lights": "Northern Lights",
    "52_NA_oslo": "Oslo",
    "53_NA_panama": "Panama",
    "54_NA_philippines": "Philippines",
    "55_NA_portugal": "Portugal",
    "56_NA_scotland": "Scotland",
    "57_NA_spain": "Spain",
    "58_NA_sweden": "Sweden",
    "59_NA_switzerland": "Switzerland",
    "60_NA_turkey": "Turkey",
    "61_NA_uk": "UK",
    "62_Na_usa": "USA",
    "63_NA_ussr": "USSR",
    "64_NA_venezuela": "Venezuela",
    "65_NA_yugoslavia": "Yugoslavia",
}

def get_map_name(map_display_name=None, map_id=None):
    """Get human-readable map name from either display name or ID"""
    if map_display_name:
        return MAP_DISPLAY_NAMES.get(map_display_name, map_display_name.replace("_", " ").title())
    elif map_id:
        return MAP_NAMES.get(map_id, f"Unknown Map ({map_id})")
    return "Unknown Map"

# Game mode conversion
GAME_MODES = {
    0: "Unknown",
    1: "Co-op",
    2: "Random", 
    3: "Ranked",
    4: "Clan",
    5: "Scenario",
    6: "Operations",
    7: "Random",  # Often used for Random battles
    8: "Training",
    9: "Brawl",
    10: "Asymmetric",
    11: "Grand Battle",
}

def get_game_mode(mode_id):
    """Get human-readable game mode"""
    return GAME_MODES.get(mode_id, f"Unknown Mode ({mode_id})")
